CXX=g++
CXXFLAGS=-g -Wall

z1857628_project2: assign2.o
	$(CXX) $(CXXFLAGS) -o z1857628_project2 assign2.o

assign2.o : assign2.cpp
	$(CXX) $(CXXFLAGS) -c assign2.cpp

clean:
	-rm *.o z1857628_project2
