CXX=g++
CXXFLAGS=-g -Wall

z1857628_project1: assign1.o
	$(CXX) $(CXXFLAGS) -o z1857628_project1 assign1.o

assign1.o : assign1.cpp
	$(CXX) $(CXXFLAGS) -c assign1.cpp

clean:
	-rm *.o z1857628_project1
